# Generated by Django 4.0.4 on 2022-07-19 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_Company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_location', models.DateField()),
                ('number_months', models.IntegerField()),
                ('end_location', models.DateField(blank=True, null=True)),
                ('empresa_name', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_value', models.FloatField()),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('can_remove', models.BooleanField(default=True)),
                ('id_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_Company.client_company')),
                ('id_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=50)),
                ('cnpj', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=17)),
                ('year', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=50)),
                ('chassi', models.CharField(max_length=21, unique=True)),
                ('license_plate', models.CharField(max_length=8)),
                ('client_name', models.CharField(max_length=50)),
                ('client_email', models.CharField(max_length=50)),
                ('client_adress', models.CharField(max_length=50)),
                ('client_city', models.CharField(max_length=50)),
                ('client_cnpj', models.CharField(max_length=50)),
                ('client_phone', models.CharField(max_length=50)),
                ('client_state', models.CharField(max_length=2)),
                ('id_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
            ],
        ),
    ]
