# Generated by Django 4.0.4 on 2022-07-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='chassi',
            field=models.CharField(max_length=21),
        ),
    ]
