# Generated by Django 4.0.6 on 2022-07-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_contract_chassi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client_adress',
            field=models.CharField(max_length=255),
        ),
    ]
