# Generated by Django 4.0.6 on 2022-07-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_contract_client_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='adress',
            field=models.CharField(max_length=255),
        ),
    ]
