# Generated by Django 4.0.6 on 2022-08-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_contract_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug_vehicle',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
