# Generated by Django 4.0.4 on 2022-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('company_name', models.CharField(max_length=80, verbose_name='company name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email adress')),
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False, verbose_name='cnpj')),
                ('password', models.CharField(max_length=88, verbose_name='password')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('adress', models.CharField(blank=True, max_length=50, null=True, verbose_name='adress company')),
                ('district', models.CharField(blank=True, max_length=50, null=True, verbose_name='district company')),
                ('city', models.CharField(max_length=30, verbose_name='city company')),
                ('state', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True, verbose_name='uf company')),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True, verbose_name='zip code company')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
